version: "3.8"

services:
  mysql_server:
    container_name: webapp_notes_db
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=webapp_notes
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-itseclab}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-itseclab}
      - MYSQL_CONNECT_TIMEOUT=60000
    networks:
      - webapp-notes-network
    ports:
      - ${WEBAPP_SERVICE_DB_PORT}:${WEBAPP_SERVICE_DB_PORT}
  app:
    container_name: webapp_notes_app
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEBAPP_SERVICE_APP_PORT}:${WEBAPP_SERVICE_APP_PORT}
    depends_on:
      - mysql_server
    networks:
      - webapp-notes-network
    command:
      [
        "/app/wait-for-it.sh",
        "mysql_server:3306",
        "-t",
        "30",
        "--",
        "npm",
        "start"
      ]
networks:
  webapp-notes-network:
    name: webapp-notes-network